### ISSUE TITLE
 Issue: Missing "Back to Top" Button

### ISSUE THREAD

**Issue by mayank-0789** [unify-ui-dev/flexilla#91]
# Issue: Missing "Back to Top" Button

## Description
The website lacks a "Back to Top" button, which negatively impacts user navigation, especially on pages with extensive content. Users are required to manually scroll back to the top, which can be cumbersome and result in a poor user experience.

### Expected Behavior:
A "Back to Top" button should be available, allowing users to smoothly scroll back to the top of the page with a single click.

### Actual Behavior:
- No "Back to Top" button is present.
- Users have to manually scroll to the top of the page, which is time-consuming 

#Screenshot
<img width="1470" alt="Screenshot 2024-10-11 at 4 00 57 AM" src="https://github.com/user-attachments/assets/90d7bb63-96c4-43b0-b37d-6ea47cfcb2f4">

**Comment by mayank-0789** [comment]
hey @unify-ui-dev please assign this issue to me

**Comment by Johnkat-Mj** [comment]
Hey @mayank-0789 

Thank you for suggesting this feature! However, considering the current layout and content of the page, which has only a few sections (hero, features, FAQ), a "Back to Top" button may not significantly improve the user experience. Since the scrollable content is minimal, users can easily navigate without the button.

Hacktoberfest is a great opportunity for contributors to engage in meaningful improvements. Perhaps we could focus on enhancing existing components, accessibility, improving current documentation or functionality that adds more value ...

Let me know if you have ideas along these lines. I’d be happy to explore other impactful contributions with you. Thanks again for your interest in helping out!
